---
- name: Generacion de Informe consolidado en un CSV
  hosts: "{{ lote | default([]) }}"
  gather_facts: false
  serial: 1
  vars_files:
    - vars/global.yml

  vars:
    log_dir: "/var/log/ansible_patches"
    out_csv_name: consolidado

  pre_tasks:
    - name: Leer resultados consolidades JSON
      when:
        - ambiente | lower == ambiente_target | lower
        - crq | lower == crq_input | lower
      ansible.builtin.slurp:
        src: "{{ log_dir }}/{{ crq_input | upper }}/{{ inventory_hostname }}/final_results_{{ inventory_hostname }}.json"
      register: final_results_file
      delegate_to: "{{ server_informes }}"
      vars:
        ansible_connection: ssh
#        ansible_user: "{{ owner }}"
#        ansible_password: "{{ ansible_pwd }}"
    #        ansible_ssh_private_key_file: ~/.ssh/id_rsa

    - name: Decodificar JSON final
      when:
        - ambiente | lower == ambiente_target | lower
        - crq | lower == crq_input | lower
      ansible.builtin.set_fact:
        results: "{{ final_results_file['content'] | b64decode | from_json }}"

    - name: Recolectar FACTS
      ansible.builtin.setup:
      ignore_unreachable: true
      register: fact_result
      retries: 5
      delay: 10
      until: not fact_result.unreachable | default(false)

    # Verificar si los facts se recopilaron correctamente
    - name: Establecer el estado de facts
      ansible.builtin.set_fact:
        facts_gathered: true
      when: ansible_os_family is defined

    - name: Manejar caso de facts fallidos
      when: facts_gathered is not defined
      block:
        - name: Creacion del archivo CSV y Encabezado
          ansible.builtin.lineinfile:
            path: "{{ log_dir }}/{{ crq_input | upper }}/{{ out_csv_name }}-{{ crq_input | upper }}.csv"
            line: "CRQ,Lote,Hostname,IP,Distribucion,Fecha,Repo_Fuente,Cantidad_Paquetes,Paquetes_Eliminados,Paquetes_Instalados,Punto_Fallo,Estado_Final"
            create: true
            state: present
            owner: "{{ owner }}"
            group: "{{ group }}"
            mode: "0755"
          delegate_to: "{{ server_informes }}"
          run_once: true
          vars:
            ansible_connection: ssh
#            ansible_user: "{{ owner }}"
#            ansible_password: "{{ ansible_pwd }}"

        - name: Escribir Columnas del CSV
          ansible.builtin.lineinfile:
            insertafter: EOF
            dest: "{{ log_dir }}/{{ crq_input | upper }}/{{ out_csv_name }}-{{ crq_input | upper }}.csv"
            line: >-
              {{ crq_input | upper }},
              {{- lote | default('N/A') }},
              {{- inventory_hostname }},
              {{- ip | default(ansible_host) }},
              {{- 'N/A' }},
              {{- 'N/A' }},
              {{- 'N/A' }},
              {{- 'N/A' }},
              {{- 'N/A' }},
              {{- 'N/A' }},
              {{- 'Validacion Previa' if not results.pre_validation.can_continue else
                  'Proceso Snapshot' if not results.snapshot.can_continue else
                  'Configuracion de Repositorio' if not results.repo_config.can_continue else
                  'Proceso de Parchado' if not results.patching.can_continue else
                  'Validacion Post-Parchado' if not results.post_validation.can_continue else
                  'Ninguno' }},
              {{- results.final_results.error.error | default('No status') }}
          delegate_to: "{{ server_informes }}"
          vars:
            ansible_connection: ssh
#            ansible_user: "{{ owner }}"
#            ansible_password: "{{ ansible_pwd }}"
  tasks:
    - name: Generacion de CSV para 'SLES'
      when:
        - facts_gathered is defined
        - ansible_os_family == 'Suse'
        - ansible_architecture == 'x86_64'
        - ambiente | lower == ambiente_target | lower
        - crq | lower == crq_input | lower
      block:
        - name: Generacion de CSV de Maquinas Familia 'Suse'
          ansible.builtin.include_role:
            name: out_csv
            tasks_from: family_suse.yml

    - name: Generacion de CSV para 'RHEL'
      when:
        - facts_gathered is defined
        - ansible_os_family == 'RedHat'
        - ansible_architecture == 'x86_64'
        - ambiente | lower == ambiente_target | lower
        - crq | lower == crq_input | lower
      block:
        - name: Generacion de CSV de Maquinas Familia 'RedHat'
          ansible.builtin.include_role:
            name: out_csv
            tasks_from: family_rhel.yml

    - name: Generacion de CSV para 'Windows'
      when:
        - facts_gathered is defined
        - ansible_os_family == 'Windows'
        - ambiente | lower == ambiente_target | lower
        - crq | lower == crq_input | lower
      block:
        - name: Generacion de CSV de Maquinas Familia 'Windows'
          ansible.builtin.include_role:
            name: out_csv
            tasks_from: family_windows.yml

- name: Lectura de Informe consolidado en un CSV
  hosts: server_informes
  gather_facts: false
  serial: 1
  vars_files:
    - vars/global.yml

  vars:
    log_dir: "/var/log/ansible_patches"
    out_csv_name: consolidado
    sharepoint_url: "https://colcomerciocom.sharepoint.com/sites/AreaInfraestructura"
    sharepoint_base_path: "/sites/AreaInfraestructura/Documentos%20compartidos"
    sharepoint_folder: "/General/Inventario%20Infraestructura/2024/Sincronizacion_Parcheado_SO/Archivos_Generados/Logs_CRQ"

  tasks:
    - name: Facts
      ansible.builtin.setup:
      vars:
        ansible_connection: ssh
#        ansible_user: "{{ owner }}"
#        ansible_password: "{{ ansible_pwd }}"

    - name: Leer contenido de archivo CSV
      ansible.builtin.command:
        cmd: cat "{{ log_dir }}/{{ crq_input | upper }}/{{ out_csv_name }}-{{ crq_input | upper }}.csv"
      register: csv_content
      changed_when: false
      vars:
        ansible_connection: ssh
#        ansible_user: "{{ owner }}"
#        ansible_password: "{{ ansible_pwd }}"

    - name: Imprimir contenido del CSV
      ansible.builtin.debug:
        var: csv_content.stdout_lines

    - name: Capturar Fecha del ZIP
      ansible.builtin.set_fact:
        fecha_crq: "{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{ ansible_date_time.second }}"

    - name: Comprimir carpeta CRQ
      community.general.archive:
        path: "{{ log_dir }}/{{ crq_input | upper }}"
        dest: "{{ log_dir }}/{{ crq_input | upper }}_{{ fecha_crq }}.zip"
        format: zip
        mode: "0755"
      vars:
        ansible_connection: ssh
#        ansible_user: "{{ owner }}"
#        ansible_password: "{{ ansible_pwd }}"

    - name: Imprimir contenido del CSV
      ansible.builtin.debug:
        var: csv_content.stdout_lines

#    - name: Subir ZIP a SharePoint
#      block:
#        - name: Subir ZIP a SharePoint
#          ansible.builtin.script:
#            cmd: roles/out_csv/files/upload_sharepoint.py
#              --file-path "{{ log_dir }}/{{ crq_input | upper }}_{{ fecha_crq }}.zip"
#              --tenant-id "{{ tenant_id }}"
#              --client-id "{{ client_id }}"
#              --client-secret "{{ client_secret }}"
#              --sharepoint-url "{{ sharepoint_url }}"
#              --sharepoint-folder "{{ sharepoint_base_path }}{{ sharepoint_folder }}"
#          register: upload_result
#          retries: 3
#          delay: 10
#          until: upload_result is success
#          changed_when: 'upload_result.stdout is search(''"success": true'')'
#          vars:
#            ansible_connection: ssh
#            ansible_user: "{{ owner }}"
#            ansible_password: "{{ ansible_pwd }}"
#
#        - name: Mostrar resultado de subida
#          ansible.builtin.debug:
#            msg: "{{ upload_result.stdout | from_json }}"
#      rescue:
#        - name: RESCUE - Subida
#          ansible.builtin.debug:
#            msg:
#              - "No se pudo subir archivo a Sharepoint, visualicelo aca:"
#              - "{{ csv_content.stdout_lines }}"
