---
- name: Buscar actualizaciones disponibles Windows
  hosts: windows
  gather_facts: true

  tasks:
    - name: Mostrar versión del sistema operativo
      ansible.builtin.debug:
        msg: >
          Versión: {{ ansible_facts.distribution }}


    - name: Buscar actualizaciones disponibles
      block:
        - name: Buscar updates
          ansible.windows.win_updates:
            category_names: "*"
            state: searched
          register: search_results
          retries: 3
          delay: 60
          until: search_results is success and search_results.found_update_count is defined

        - name: DEBUG
          ansible.builtin.debug:
            var: search_results
