---
# vars file for roles/validacion_previa

# Definición de espacios mínimos por filesystem
validacion_previa_fs_space_requirements:
  root: # root es igual que /
    all_separate: 1000 # 3000 # Cuando todos los FS están separados
    with_boot: 3500 # Con /boot montado
    with_tmp: 4000 # Con /tmp montado
    with_var: 5000 # Con /var montado
    with_usr: 5000 # Con /usr montado
    no_boot_usr: 5500 # Sin /boot y /usr
    no_boot_var: 5500 # Sin /boot y /var
    no_boot_tmp: 4500 # Sin /boot y /tmp
    no_usr_tmp: 7000 # Sin /usr y /tmp
    no_usr_var: 7000 # Sin /usr y /var
    no_tmp_var: 7000 # Sin /tmp y /var
    no_tmp_var_boot: 6500 # Sin /tmp, /var y /boot
    no_tmp_var_usr: 5000 # Sin /tmp, /var y /usr
    default: 8500 # Todos montados en /
  separate_fs:
    boot: 50
    usr: 2000
    var: 2000
    tmp: 1000
