servers_supported = [
    'Red Hat Enterprise Linux Server release 7.3',
    'Red Hat Enterprise Linux Server release 7.8',
    'Red Hat Enterprise Linux Server release 7.9',
    'Red Hat Enterprise Linux release 8.3',
    'Red Hat Enterprise Linux 8.8',
    'Red Hat Enterprise Linux Server 9.4',
    'SUSE Linux Enterprise Server 15 SP4',
    'SUSE Linux Enterprise Server 15 SP5',
    'SUSE Linux Enterprise Desktop 15 SP5',
    'CentOS Linux release 7.1.1503',
    'CentOS Linux release 7.3.1611',
    'CentOS Linux release 7.5.1804',
    'CentOS Linux release 7.6.1810',
    'CentOS Linux release 7.7.1908',
    'CentOS Linux release 7.9.2009',
    'CentOS Linux release 8.2.2004',
    'Oracle Linux Server release 8.4',
    'Oracle Linux Server release 8.5',
    'Oracle Linux Server release 8.6',
    'Oracle Linux Server release 8.7',
    'Oracle Linux Server release 8.8',
    'Oracle Linux Server release 8.9',
    'Oracle Linux Server 8.9',
    'Oracle Linux Server 9.4',
    'Windows Server 2012 Standard',
    'Windows Server 2012 R2 Standard',
    'Windows Server 2012 R2 Datacenter',
    'Windows Server 2016 Standard',
    "Windows Server 2016 Datacenter",
    "Windows Server 2019 Datacenter",
    "Windows Server 2019 Standard",
    'Windows Server 2022 Standard'
]