# ===============================================
# INVENTARIO ANSIBLE - INFRASTRUCTURA CLARO
# ===============================================
[windows:children]
lote_2

# ===============================================
# SERVIDORES WINDOWS
# ===============================================
[lote_2]
LABMCPGIR1 ansible_host=172.27.181.99 ambiente=produccion crq=CRQDUMMYC0 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''
LABMCPGIR2 ansible_host=172.27.181.100 ambiente=produccion crq=CRQDUMMYC0 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''
FormulariosServer1 ansible_host=172.27.181.101 ambiente=produccion crq=CRQDUMMYC0 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''
FormulariosServer2 ansible_host=172.27.181.102 ambiente=produccion crq=CRQDUMMYC0 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''
SM_DB_SQL1 ansible_host=172.27.181.120 ambiente=produccion crq=CRQDUMMYC0 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''
SM_DB_SQL2 ansible_host=172.27.181.121 ambiente=produccion crq=CRQDUMMYC0 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''
# LabMCPGIR4 ansible_host=172.27.181.122

[lote_2:vars]
ansible_connection = winrm
ansible_winrm_scheme = https
ansible_winrm_message_encryption = auto
ansible_winrm_transport=ntlm
ansible_winrm_port=5986
ansible_winrm_server_cert_validation = ignore
ansible_winrm_operation_timeout_sec=600
ansible_winrm_read_timeout_sec=900
ansible_winrm_connection_timeout=900

[server_informes]
ansibleawx ansible_host=10.2.0.4

[server_informes:vars]
ansible_connection=ssh
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o PreferredAuthentications=password -o PubkeyAuthentication=no'
