# ===============================================
# INVENTARIO ANSIBLE - INFRASTRUCTURA CLARO
# ===============================================

# ===============================================
# SERVIDORES LINUX
# ===============================================
[linux]
CORELABServer1 ansible_host=172.27.181.115
CORELABServer2 ansible_host=172.27.181.98
E-servicesServer1 ansible_host=172.27.181.117
E-servicesServer2 ansible_host=172.27.181.116
TelefoniaServer1 ansible_host=172.18.204.107
TelefoniaServer2 ansible_host=172.18.204.108
TELEFONIA3 ansible_host=172.18.204.109
telefoniaserver4 ansible_host=172.18.204.110
WFMSserver1 ansible_host=172.27.181.103
WFMSserver2 ansible_host=172.27.181.104
ReporteriaServer1 ansible_host=172.27.181.105
ReporteriaServer2 ansible_host=172.27.181.106
GMSCassandraORSSer1 ansible_host=172.27.181.107
GMSCassandraORSSer2 ansible_host=172.27.181.108
GMSCassandraORSSer3 ansible_host=172.27.181.109
LabGirRHL1Ser1 ansible_host=172.27.181.110
LabGirRHL1Ser2 ansible_host=172.27.181.114
LabGirRHL1Ser3 ansible_host=172.27.181.112
LabGirRHL2Ser1 ansible_host=172.27.181.111
LabGirRHL2Ser2 ansible_host=172.27.181.113
SM_DB_FISICO ansible_host=172.27.181.119

[linux:vars]
ansible_connection=ssh
ansible_user=46304918
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3

# ===============================================
# SERVIDORES WINDOWS
# ===============================================
[windows]
LABMCPGIR1 ansible_host=172.27.181.99
LABMCPGIR2 ansible_host=172.27.181.100
LabMCPGIR4 ansible_host=172.27.181.122
FormulariosServer1 ansible_host=172.27.181.101
FormulariosServer2 ansible_host=172.27.181.102
SM_DB_SQL1 ansible_host=172.27.181.120
SM_DB_SQL2 ansible_host=172.27.181.121

[windows:vars]
ansible_connection=winrm
ansible_user=Administrador
ansible_password=TuPassword
ansible_port=5986
ansible_winrm_scheme=https
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=ntlm

# ===============================================
# GRUPOS GLOBALES
# ===============================================
[all_linux_servers:children]
linux

[all_windows_servers:children]
windows

# ===============================================
# VARIABLES GLOBALES
# ===============================================
[all:vars]
# vars