# ===============================================
# INVENTARIO ANSIBLE - INFRASTRUCTURA CLARO
# ===============================================

# ===============================================
# SERVIDORES LINUX
# ===============================================
[linux]
CORELABServer1 ansible_host=172.27.181.115 ansible_user=46304918 ansible_ssh_pass='Pc@ssN$x@.0925/*' ansible_become_method=sudo ansible_become_user=root
CORELABServer2 ansible_host=172.27.181.98 ansible_user=46304918 ansible_ssh_pass='Pc@ssN$x@.0925/*' ansible_become_method=sudo ansible_become_user=root
E-servicesServer1 ansible_host=172.27.181.117 ansible_user=46304918 ansible_ssh_pass='Pc@ssN$x@.0925/*' ansible_become_method=sudo ansible_become_user=root

[linux:vars]
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=auto_silent

# ===============================================
# SERVIDORES WINDOWS
# ===============================================
[windows]
# LABMCPGIR1 ansible_host=172.27.181.99
LABMCPGIR2 ansible_host=172.27.181.100
FormulariosServer1 ansible_host=172.27.181.101
FormulariosServer2 ansible_host=172.27.181.102
SM_DB_SQL1 ansible_host=172.27.181.120
SM_DB_SQL2 ansible_host=172.27.181.121
# LabMCPGIR4 ansible_host=172.27.181.122

[windows:vars]
ansible_user = autontt
ansible_password = T4mP0ral2025*
ansible_connection = winrm
ansible_winrm_scheme = http
ansible_winrm_message_encryption = auto
ansible_winrm_transport=ntlm
ansible_winrm_port=5985
ansible_winrm_server_cert_validation = ignore
ansible_winrm_operation_timeout_sec=600
ansible_winrm_read_timeout_sec=900
ansible_winrm_connection_timeout=900

# ===============================================
# GRUPOS GLOBALES
# ===============================================
[all_linux_servers:children]
linux

[all_windows_servers:children]
windows

# ===============================================
# VARIABLES GLOBALES
# ===============================================
[all:vars]
# vars