# ===============================================
# INVENTARIO ANSIBLE - INFRASTRUCTURA CLARO
# ===============================================
[linux:children]
lote_1

[windows:children]
lote_2

# ===============================================
# SERVIDORES LINUX
# ===============================================
[lote_1]
CORELABServer1 ansible_host=172.27.181.115 ambiente=produccion crq=CRQDUMMYC1 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''
CORELABServer2 ansible_host=172.27.181.98 ambiente=produccion crq=CRQDUMMYC1 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''
E-servicesServer1 ansible_host=172.27.181.117 ambiente=produccion crq=CRQDUMMYC1 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''

[lote_1:vars]
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=auto_silent

# ===============================================
# SERVIDORES WINDOWS
# ===============================================
[lote_2]
LABMCPGIR1 ansible_host=172.27.181.99 ambiente=produccion crq=CRQDUMMYC0 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''
LABMCPGIR2 ansible_host=172.27.181.100 ambiente=produccion crq=CRQDUMMYC0 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''
FormulariosServer1 ansible_host=172.27.181.101 ambiente=produccion crq=CRQDUMMYC0 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''
FormulariosServer2 ansible_host=172.27.181.102 ambiente=produccion crq=CRQDUMMYC0 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''
SM_DB_SQL1 ansible_host=172.27.181.120 ambiente=produccion crq=CRQDUMMYC0 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''
SM_DB_SQL2 ansible_host=172.27.181.121 ambiente=produccion crq=CRQDUMMYC0 tipo_vmware='' vm_name='' vcenter_vmware='' datacenter_vmware=''
# LabMCPGIR4 ansible_host=172.27.181.122

[lote_2:vars]
# ansible_user = autontt
# ansible_password = T4mP0ral2025*
ansible_connection = winrm
ansible_winrm_scheme = https
ansible_winrm_message_encryption = auto
ansible_winrm_transport=ntlm
ansible_winrm_port=5986
ansible_winrm_server_cert_validation = ignore
ansible_winrm_operation_timeout_sec=600
ansible_winrm_read_timeout_sec=900
ansible_winrm_connection_timeout=900
